
name: Trigger Netlify Build
on:
  schedule:
    # “At minute 0 past every hour from 13 through 22 on every day-of-week from Monday through Friday.”
    # https://crontab.guru/#0_7-22_*_*_1-5
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60736b98a49b013a4d569fa7
